
from pathlib import Path
from decouple import config
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# In Docker: AUTO-GENERATED by entrypoint.sh on first run
# Priority: 1) Environment variable, 2) File in Docker, 3) .env file (local dev)
def get_secret_key():
    """Get SECRET_KEY from environment, file (Docker), or .env (local dev)"""
    import os
    from pathlib import Path

    # Try environment variable first (set by entrypoint.sh or docker-compose)
    secret = os.environ.get('SECRET_KEY')
    if secret:
        return secret

    # Try reading from Docker config file
    secret_file = Path('/usr/src/app/config/secret_key.txt')
    if secret_file.exists():
        return secret_file.read_text().strip()

    # Fall back to .env file for local development
    return config('SECRET_KEY')

SECRET_KEY = get_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = [h.strip() for h in config('ALLOWED_HOSTS', default='').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'rest_framework',
    'drf_yasg',
    # 'channels',  # Temporalmente comentado para tests
    # Project apps
    'core',
    'users',
    'auth_system',
    'audit',
    'dataset',
    'api',  # API for RESEARCHER users
    'trainings',  # Training monitoring system
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'users.middleware.SessionTimeoutMiddleware',
    'users.middleware.APIAuthenticationMiddleware',  # API authentication for /api/ endpoints
    'users.middleware.RateLimitMiddleware',          # Rate limiting for API endpoints
    'audit.middleware.AuditMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'medinet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.nav_permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'medinet.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db' / 'users_logs.sqlite3',
    },
    'datasets_db': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db' / 'datasets.sqlite3',
    },
}

# Optional DATABASE_URL overrides (for deployments)
default_db_url = config('DATABASE_URL', default=None)
if default_db_url:
    DATABASES['default'] = dj_database_url.parse(default_db_url, conn_max_age=600)

datasets_db_url = config('DATASETS_DATABASE_URL', default=None)
if datasets_db_url:
    DATABASES['datasets_db'] = dj_database_url.parse(datasets_db_url, conn_max_age=600)

DATABASE_ROUTERS = ['core.routers.DatabaseRouter']


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'users.validators.MedicalPasswordValidator',
    },
    {
        'NAME': 'users.validators.PasswordHistoryValidator',
    },
]

AUTH_USER_MODEL = 'users.CustomUser'

AUTHENTICATION_BACKENDS = [
    'auth_system.backends.SecureLoginBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Authentication redirects
LOGIN_URL = 'login'
# LOGIN_REDIRECT_URL removed - now using role-based redirects in login_page view
LOGOUT_REDIRECT_URL = 'login'

# Security controls
ACCOUNT_LOCKOUT_ATTEMPTS = 5
ACCOUNT_LOCKOUT_DURATION = 300  # seconds
SESSION_IDLE_TIMEOUT = 7200  # 2 hours (was 30 minutes - increased to prevent logout during training monitoring)

# Session security settings
SESSION_COOKIE_AGE = SESSION_IDLE_TIMEOUT
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_SECURE = not DEBUG  # Secure cookies in production
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_SAVE_EVERY_REQUEST = True
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Use database sessions for better reliability

# CSRF Protection settings
CSRF_COOKIE_SECURE = not DEBUG  # Secure cookies in production
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_FAILURE_VIEW = 'auth_system.views.csrf_failure'
CSRF_TRUSTED_ORIGINS = [
    'https://localhost',
    'https://127.0.0.1',
    'http://localhost',
    'http://127.0.0.1',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost:8001',
    'http://127.0.0.1:8001',
]

# Cache configuration for rate limiting
redis_url = config('REDIS_URL', default=None)
if redis_url:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': redis_url,
            'OPTIONS': {
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 50,
                    'retry_on_timeout': True,
                },
            },
            'KEY_PREFIX': 'medinet:',
            'TIMEOUT': 300,  # 5 minutes default
        }
    }
else:
    # Development uses in-memory cache to avoid DB table requirement; production uses DB cache
    if DEBUG:
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
                'LOCATION': 'medinet-dev-cache',
            }
        }
    else:
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
                'LOCATION': 'cache_table',
            }
        }

# Django-ratelimit settings
RATELIMIT_USE_CACHE = 'default'
RATELIMIT_ENABLE = True

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Europe/Madrid'
USE_I18N = True
USE_TZ = True


STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # For collectstatic in production
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
DATASETS_STORAGE_DIR = BASE_DIR / 'datasets'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{asctime}] {levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'medinet.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 3,
            'formatter': 'verbose',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'security.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.server': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'security': {
            'handlers': ['security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # We use custom API key authentication, not DRF's built-in auth
    ],
}

# Swagger/OpenAPI Configuration
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'API Key': {
            'type': 'apiKey',
            'name': 'X-API-Key',
            'in': 'header'
        },
        'Client IP': {
            'type': 'apiKey',
            'name': 'X-Client-IP',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False,
    'LOGIN_URL': None,
    'LOGOUT_URL': None,
}
