# Generated by Django 4.2.23 on 2025-08-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('INVESTIGADOR', 'INVESTIGADOR'), ('AUDITOR', 'AUDITOR')], max_length=50, unique=True),
        ),
    ]
