# Generated by Django 5.2.3 on 2025-08-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('RESEARCHER', 'RESEARCHER'), ('AUDITOR', 'AUDITOR')], max_length=50, unique=True),
        ),
    ]
