# Generated by Django 4.2.23 on 2025-08-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_apikey_regeneration_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='last_regenerated_at',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='regenerated_count',
        ),
    ]
