# Generated by Django 5.2.3 on 2026-01-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial_squashed_0007_remove_apikey_last_regenerated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('MEMBER', 'MEMBER'), ('RESEARCHER', 'RESEARCHER'), ('AUDITOR', 'AUDITOR')], max_length=50, unique=True),
        ),
    ]
