# Generated by Django 5.2.3 on 2026-01-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_role_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='apikey',
            name='users_apike_key_fe45f4_idx',
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='key',
        ),
        migrations.AddField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(blank=True, help_text='Hashed API key for secure authentication (stores hash, not plaintext)', max_length=128, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key_hash'], name='users_apike_key_has_5d53ed_idx'),
        ),
    ]
