# Generated by Django 5.2.3 on 2026-01-24 11:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for the model', max_length=200)),
                ('version', models.CharField(default='1.0.0', help_text='Semantic version (e.g., 1.0.0)', max_length=50)),
                ('description', models.TextField(help_text='Detailed description of model purpose and usage')),
                ('domain', models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('oncology', 'Oncology'), ('radiology', 'Radiology'), ('pathology', 'Pathology'), ('general', 'General Medicine')], help_text='Medical domain for this model', max_length=50)),
                ('model_file', models.FileField(help_text='ONNX model file (.onnx)', upload_to='inference/models/%Y/%m/')),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('checksum', models.CharField(blank=True, help_text='SHA256 checksum of model file', max_length=64)),
                ('input_schema', models.JSONField(help_text='Expected input format: {feature_names: [str], dtypes: {feature: dtype}, shape: [int]}')),
                ('output_schema', models.JSONField(help_text='Output format: {output_names: [str], dtypes: {output: dtype}, shape: [int]}')),
                ('is_public', models.BooleanField(default=False, help_text='Public models are accessible to all users with inference.execute permission')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('deprecated', 'Deprecated'), ('rejected', 'Rejected')], default='pending', help_text='Approval status of the model', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp when model was approved', null=True)),
                ('source', models.CharField(choices=[('training', 'From Training'), ('upload', 'Manual Upload')], default='upload', help_text='Origin of this model', max_length=20)),
                ('training_session_id', models.CharField(blank=True, help_text='Reference to training session if source=training', max_length=100)),
                ('accuracy', models.FloatField(blank=True, help_text='Model accuracy (0.0 to 1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('validation_notes', models.TextField(blank=True, help_text='Validation results and notes from testing')),
                ('max_requests_per_minute', models.IntegerField(default=60, help_text='Maximum requests per minute per user', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_batch_size', models.IntegerField(default=1000, help_text='Maximum number of rows per prediction request', validators=[django.core.validators.MinValueValidator(1)])),
                ('enable_differential_privacy', models.BooleanField(default=False, help_text='Add noise to predictions for privacy protection')),
                ('dp_epsilon', models.FloatField(default=1.0, help_text='Differential privacy epsilon parameter (lower = more privacy)', validators=[django.core.validators.MinValueValidator(0.01)])),
                ('dp_noise_scale', models.FloatField(default=0.1, help_text='Scale of noise to add to predictions', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_predictions', models.BigIntegerField(default=0, help_text='Total number of predictions made with this model')),
                ('last_prediction_at', models.DateTimeField(blank=True, help_text='Timestamp of last prediction', null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved this model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_models', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain', 'status'], name='inference_d_domain_bd1d91_idx'), models.Index(fields=['uploaded_by', '-created_at'], name='inference_d_uploade_8f770d_idx'), models.Index(fields=['status', 'is_public'], name='inference_d_status_2f67c5_idx')],
                'unique_together': {('name', 'version')},
            },
        ),
    ]
