# Generated by Django 5.2.3 on 2026-01-24 11:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0001_initial'),
        ('users', '0008_alter_role_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the requester')),
                ('model_name', models.CharField(help_text='Model name snapshot (in case model is deleted)', max_length=200)),
                ('model_version', models.CharField(help_text='Model version snapshot', max_length=50)),
                ('model_domain', models.CharField(help_text='Model domain snapshot', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the prediction was made')),
                ('records_count', models.IntegerField(help_text='Number of records in the prediction batch')),
                ('execution_time_ms', models.IntegerField(help_text='Execution time in milliseconds')),
                ('rate_limit_remaining', models.IntegerField(help_text='Remaining requests in rate limit window')),
                ('suspicious_score', models.FloatField(default=0.0, help_text='Suspicion score from pattern detection (0.0 = normal, 1.0 = very suspicious)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('patterns_detected', models.JSONField(default=list, help_text="List of suspicious patterns detected (e.g., ['rapid_fire', 'exhaustive_search'])")),
                ('input_hash', models.CharField(help_text='SHA256 hash of input data (for duplicate detection, privacy-preserving)', max_length=64)),
                ('success', models.BooleanField(default=True, help_text='Whether the prediction succeeded')),
                ('error_message', models.TextField(blank=True, help_text='Error message if prediction failed')),
                ('dp_noise_applied', models.BooleanField(default=False, help_text='Whether differential privacy noise was applied to this prediction')),
                ('api_key', models.ForeignKey(blank=True, help_text='API key used for the request (if via API)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediction_audits', to='users.apikey')),
                ('model', models.ForeignKey(help_text='Model used for prediction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediction_audits', to='inference.deployedmodel')),
                ('user', models.ForeignKey(help_text='User who made the prediction request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediction_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prediction_audit',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='prediction__user_id_cf667d_idx'), models.Index(fields=['model', '-timestamp'], name='prediction__model_i_86f14f_idx'), models.Index(fields=['-timestamp'], name='prediction__timesta_118dc6_idx'), models.Index(fields=['suspicious_score', '-timestamp'], name='prediction__suspici_941a03_idx'), models.Index(fields=['ip_address', '-timestamp'], name='prediction__ip_addr_bf405c_idx'), models.Index(fields=['input_hash'], name='prediction__input_h_446f55_idx')],
            },
        ),
    ]
