# Generated by Django 5.2.3 on 2025-12-09 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('audit', '0001_initial'), ('audit', '0002_initial'), ('audit', '0003_auditevent_dataaccesslog_securityincident_and_more')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('resource', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('resource', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('category', models.CharField(choices=[('AUTH', 'Authentication'), ('DATA_ACCESS', 'Data Access'), ('USER_MGMT', 'User Management'), ('DATASET_MGMT', 'Dataset Management'), ('TRAINING', 'Federated Training'), ('API', 'API Access'), ('SYSTEM', 'System Operations')], default='SYSTEM', max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical'), ('SECURITY', 'Security Event')], default='INFO', max_length=10)),
                ('risk_score', models.IntegerField(default=0, help_text='Risk score 0-100')),
                ('session_id', models.CharField(blank=True, max_length=40)),
                ('user_agent', models.TextField(blank=True)),
                ('request_size', models.IntegerField(blank=True, help_text='Request size in bytes', null=True)),
                ('request_duration_ms', models.IntegerField(blank=True, null=True)),
                ('requires_review', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_audit_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DataAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_domain', models.CharField(blank=True, help_text='Medical specialty domain', max_length=100)),
                ('patient_count_accessed', models.IntegerField(default=0)),
                ('data_sensitivity_level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=1, help_text='Data sensitivity level 1-5')),
                ('columns_accessed', models.JSONField(blank=True, default=list)),
                ('records_accessed', models.IntegerField(default=0)),
                ('query_hash', models.CharField(blank=True, help_text='Hash of executed query', max_length=64)),
                ('audit_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_access_log', to='audit.auditevent')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('UNAUTHORIZED_ACCESS', 'Unauthorized Access Attempt'), ('DATA_BREACH_ATTEMPT', 'Data Breach Attempt'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity'), ('MULTIPLE_FAILED_AUTH', 'Multiple Failed Authentication'), ('PRIVILEGE_ESCALATION', 'Privilege Escalation Attempt'), ('ANOMALOUS_PATTERN', 'Anomalous Access Pattern')], max_length=30)),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Under Investigation'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=15)),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('resolution_notes', models.TextField(blank=True)),
                ('risk_score', models.IntegerField(default=0, help_text='Aggregated risk score from related events')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('related_events', models.ManyToManyField(help_text='Audit events that triggered this incident', related_name='security_incidents', to='audit.auditevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['action'], name='audit_audit_action_203f66_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['timestamp'], name='audit_audit_timesta_ee9c56_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['category'], name='audit_audit_categor_b9a693_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['severity'], name='audit_audit_severit_7bcd1f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['risk_score'], name='audit_audit_risk_sc_8c6fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['requires_review'], name='audit_audit_require_b367e1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_314539_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['ip_address', 'timestamp'], name='audit_audit_ip_addr_e0eb10_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['category', 'severity'], name='audit_audit_categor_e74b2d_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccesslog',
            index=models.Index(fields=['medical_domain'], name='audit_dataa_medical_00f4d8_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccesslog',
            index=models.Index(fields=['data_sensitivity_level'], name='audit_dataa_data_se_5cf83f_idx'),
        ),
        migrations.AddIndex(
            model_name='dataaccesslog',
            index=models.Index(fields=['patient_count_accessed'], name='audit_dataa_patient_08b6fa_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['incident_type'], name='audit_secur_inciden_bedf52_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['state'], name='audit_secur_state_eaf8ad_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['severity'], name='audit_secur_severit_e55661_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['created_at'], name='audit_secur_created_2bb82b_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['assigned_to'], name='audit_secur_assigne_d62b1f_idx'),
        ),
    ]
