# Generated by Django 4.2.23 on 2025-08-29 15:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(blank=True, help_text='Flower client ID', max_length=100, null=True)),
                ('dataset_id', models.IntegerField(help_text='Dataset ID from datasets_db')),
                ('dataset_name', models.CharField(help_text='Dataset name for display', max_length=200)),
                ('model_config', models.JSONField(default=dict, help_text='Complete model configuration JSON')),
                ('server_address', models.CharField(default='localhost:8080', max_length=200)),
                ('total_rounds', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('status', models.CharField(choices=[('STARTING', 'Starting'), ('ACTIVE', 'Training Active'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='STARTING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration', models.DurationField(blank=True, null=True)),
                ('current_round', models.PositiveIntegerField(default=0)),
                ('progress_percentage', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('cpu_usage', models.FloatField(blank=True, help_text='CPU usage percentage', null=True)),
                ('memory_usage', models.FloatField(blank=True, help_text='Memory usage in MB', null=True)),
                ('process_id', models.PositiveIntegerField(blank=True, help_text='Training process PID', null=True)),
                ('final_accuracy', models.FloatField(blank=True, null=True)),
                ('final_loss', models.FloatField(blank=True, null=True)),
                ('final_precision', models.FloatField(blank=True, null=True)),
                ('final_recall', models.FloatField(blank=True, null=True)),
                ('final_f1', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_traceback', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='User who initiated training', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('loss', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('metrics', models.JSONField(default=dict, help_text='Additional round-specific metrics')),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('memory_usage', models.FloatField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='trainings.trainingsession')),
            ],
            options={
                'ordering': ['session', 'round_number'],
            },
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['user', 'status'], name='trainings_t_user_id_5c0928_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['started_at'], name='trainings_t_started_0621d4_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['status'], name='trainings_t_status_2ba9c1_idx'),
        ),
        migrations.AddIndex(
            model_name='traininground',
            index=models.Index(fields=['session', 'round_number'], name='trainings_t_session_5205df_idx'),
        ),
        migrations.AddIndex(
            model_name='traininground',
            index=models.Index(fields=['started_at'], name='trainings_t_started_1f4afa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='traininground',
            unique_together={('session', 'round_number')},
        ),
    ]
