# Generated by Django 5.2.3 on 2025-12-09 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_remove_flower_fields')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_id', models.CharField(help_text='Identificador único del centro en la red MediNet (lowercase, alfanumérico con guiones)', max_length=20, unique=True)),
                ('center_display_name', models.CharField(help_text='Nombre completo del centro médico para mostrar', max_length=200)),
                ('center_email', models.EmailField(blank=True, help_text='Email de contacto del centro médico', max_length=254, null=True)),
                ('extra_settings', models.JSONField(blank=True, default=dict, help_text='Configuraciones adicionales en formato JSON (extensible para futuras features)')),
                ('setup_completed_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se completó el setup inicial')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Última modificación de la configuración')),
                ('setup_completed_by', models.ForeignKey(blank=True, help_text='Usuario que completó el setup inicial', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_setup', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
