# Generated by Django 5.2.3 on 2025-12-08 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='flower_port',
        ),
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='flower_url',
        ),
    ]
